# This file was generated by GoReleaser. DO NOT EDIT.
cask "outpost" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "ce059f758bf227a995b66ad3f881c5c968b44684da81083f4de4d5c0754501ac"
      url "https://github.com/godx-jp/godx-outpost/releases/download/v#{version}/outpost_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "733d1c96d06c9731c9b6c98a2bd117ebe37d8e50cc3892f158de56ce8ef9b880"
      url "https://github.com/godx-jp/godx-outpost/releases/download/v#{version}/outpost_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "06e55369ff719025aa70c801d68597d56088b1b3bf7f7d042fe741cc622a3080"
      url "https://github.com/godx-jp/godx-outpost/releases/download/v#{version}/outpost_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "66bdbfb7f88e7841ddfcf2a86b4ae063ee59cf933244c62bb6fb2ac896a77f32"
      url "https://github.com/godx-jp/godx-outpost/releases/download/v#{version}/outpost_#{version}_linux_arm64.tar.gz"
    end
  end

  name "outpost"
  desc "Outpost — remote-access host daemon (terminal/files/monitor over WebSocket)"
  homepage "https://github.com/godx-jp/godx-outpost"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "outpost"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/outpost"]
    end
  end

  # No zap stanza required

end
